services:
  db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  django-web:
   build: .
   container_name: credit_approval_system_django
   ports:
     - "8000:8000"
   depends_on:
     - db 
     - redis
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
    
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
 
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
     
   env_file:
     - .env 

  celery-worker:
    build: .
    container_name: celery_worker
    command: celery -A credit_approval_system worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env

volumes:
   postgres_data: